kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: slack_demo
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 1m
 
    receivers:
    - name: slack_demo
      slack_configs:
      - api_url: https://hooks.slack.com/services/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
        channel: '#test-alerts'
